name       : haskell-monad-logger
version    : 0.3.20.2
release    : 1
source     :
    - http://hackage.haskell.org/package/monad-logger-0.3.20.2/monad-logger-0.3.20.2.tar.gz : 1f004999b282b3895cc0904053befb48b863efc2899a89e93195b4544cc9c737
license    : MIT
component  : programming.haskell
summary    : A monad transformer approach for logging.
description: |
    A monad transformer approach for logging.
builddeps  :
    - haskell-cabal-install
    - haskell-conduit-extra
    - haskell-fast-logger
    - haskell-monad-loops
    - haskell-stm-chans
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
