name       : haskell-monad-logger
version    : 0.3.36
release    : 3
source     :
    - https://hackage.haskell.org/package/monad-logger-0.3.36/monad-logger-0.3.36.tar.gz : 706d403f37a84d87ac83b79320e18f55cf15739daf4327aac411ce17c0043c8b
license    : MIT
component  : programming.haskell
summary    : A monad transformer approach for logging.
description: |
    A monad transformer approach for logging.
builddeps  :
    - haskell-cabal-install
    - haskell-conduit-extra-devel
    - haskell-fast-logger-devel
    - haskell-lifted-base-devel
    - haskell-monad-loops-devel
    - haskell-stm-chans-devel
rundeps    :
    - devel:
        - haskell-conduit-extra-devel
        - haskell-fast-logger-devel
        - haskell-lifted-base-devel
        - haskell-monad-loops-devel
        - haskell-stm-chans-devel
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
