name       : haskell-monad-logger
version    : 0.3.28.5
release    : 2
source     :
    - http://hackage.haskell.org/package/monad-logger-0.3.28.5/monad-logger-0.3.28.5.tar.gz : 225ed7cd2d0d375c0207d5d3b9faa12b339ca7dd51ca92f96d3eaf2d360027f1
license    : MIT
component  : programming.haskell
summary    : A monad transformer approach for logging.
description: |
    A monad transformer approach for logging.
builddeps  :
    - haskell-cabal-install
    - haskell-conduit-extra
    - haskell-fast-logger
    - haskell-lifted-base
    - haskell-monad-control
    - haskell-monad-loops
    - haskell-stm-chans
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
